[platformio]
default_envs = code_pet

[env:code_pet]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/Adafruit NeoPixel@^1.12.3
build_flags =
  -DCODE_PET_DISPLAY_OLED
  -DCODE_PET_HAS_BLE
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCODE_PET_DEVICE_NAME=\"VibePet-ESP-AI-DIY-S3-OLED\"
  -DCODE_PET_STATUS_PIXEL
  -DCP_STATUS_PIXEL_PIN=46
  -DCP_STATUS_PIXEL_BRIGHTNESS=56
  -DCP_OLED_WIDTH=128
  -DCP_OLED_HEIGHT=64
  -DCP_OLED_SDA=39
  -DCP_OLED_SCL=38
  -DCP_OLED_RST=-1
