[platformio]
default_envs = code_pet

[env:code_pet]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit SSD1306@^2.5.13
build_flags =
  -DCODE_PET_DISPLAY_OLED
  -DCODE_PET_HAS_BLE
  -DCODE_PET_DEVICE_NAME=\"VibePet-Heltec-WiFi-Kit-32\"
  -DCP_OLED_WIDTH=128
  -DCP_OLED_HEIGHT=64
  -DCP_OLED_SDA=4
  -DCP_OLED_SCL=15
  -DCP_OLED_RST=16
