#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_TXT_ENC LV_TXT_ENC_UTF8

#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (64U * 1024U)

#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_DISP_DEF_REFR_PERIOD 33
#define LV_DPI_DEF 130

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_SIMSUN_16_CJK 0
#define LV_USE_FONT_COMPRESSED 0
#define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(lv_font_code_pet_cn_16)
#define LV_FONT_DEFAULT &lv_font_code_pet_cn_16

#define LV_USE_THEME_DEFAULT 1
#define LV_USE_LABEL 1
#define LV_USE_IMG 1

#endif
